[versions]
# Adventure
adventure = "4.26.1"  # https://github.com/PaperMC/adventure
adventure-platform = "4.4.1"  # https://github.com/PaperMC/adventure-platform
adventure-platform-mod = "6.8.0"  # https://github.com/PaperMC/adventure-platform-mod

# Cloud
cloud = "2.0.0"  # https://github.com/Incendo/cloud
cloud-minecraft = "2.0.0-beta.14"  # https://github.com/Incendo/cloud-minecraft
cloud-minecraft-modded = "2.0.0-beta.15"  # https://github.com/Incendo/cloud-minecraft-modded

# Server APIs
bungeecord-api = "1.21-R0.1"
spigot-api = "1.21.11-R0.1-SNAPSHOT"
paper-api = "1.21.11-R0.1-SNAPSHOT"
velocity-api = "3.5.0-SNAPSHOT"

# Modding
minecraft = "1.21.11"
fabric-loader = "0.18.4"
fabric-api = "0.141.3+1.21.11"
fabric-permissions-api = "0.6.1"
neoforge = "21.11.38-beta"

configurate = "4.2.0-GeyserMC-SNAPSHOT"
slf4j = "2.0.17"

[plugins]
blossom = { id = "net.kyori.blossom", version = "2.2.0" }
indra-git = { id = "net.kyori.indra.git", version = "4.0.0" }

[libraries]
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-bungeecord = { group = "net.kyori", name = "adventure-platform-bungeecord", version.ref = "adventure-platform" }
adventure-fabric = { group = "net.kyori", name = "adventure-platform-fabric", version.ref = "adventure-platform-mod" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-neoforge = { group = "net.kyori", name = "adventure-platform-neoforge", version.ref = "adventure-platform-mod" }

cloud-bungeecord = { group = "org.incendo", name = "cloud-bungee", version.ref = "cloud-minecraft" }
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-fabric = { group = "org.incendo", name = "cloud-fabric", version.ref = "cloud-minecraft-modded" }
cloud-neoforge = { group = "org.incendo", name = "cloud-neoforge", version.ref = "cloud-minecraft-modded" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-minecraft" }
cloud-velocity = { group = "org.incendo", name = "cloud-velocity", version.ref = "cloud-minecraft" }

# Config and YAML Libraries
configurate-interface-ap = { group = "org.spongepowered", name = "configurate-extra-interface-ap", version.ref = "configurate" }
configurate-interface = { group = "org.spongepowered", name = "configurate-extra-interface", version.ref = "configurate" }
configurate-yaml = { group = "org.spongepowered", name = "configurate-yaml", version.ref = "configurate" }

minecraft = { group = "net.minecraft", name = "minecraft", version.ref = "minecraft" }

fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-permissions-api = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric-permissions-api" }

# Logging Libraries
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-jdk14 = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }

# Server APIs
bungeecord-api = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord-api" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot-api" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity-api" }

# Gradle Plugins
checkstyle = { group = "com.puppycrawl.tools", name = "checkstyle", version = "13.2.0" }
lombok-plugin = { group = "io.freefair.gradle", name = "lombok-plugin", version = "9.2.0" }
shadow-plugin = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version = "9.3.1" }
spotless-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "8.2.1" }
